kind: pipeline
type: docker
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: ollioddi/linefever
    auto_tag: true
    registry: https://dockerregistry.ollioddi.dk
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password