kind: pipeline
type: docker
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: dockerregistry.ollioddi.dk/ollioddi/linefever
    registry: dockerregistry.ollioddi.dk
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password