kind: pipeline
type: docker
name: prod
steps:
    - name: test
      image: node
      commands:
          - npm install
          - npm test
    - name: docker_build
      image: plugins/docker
      settings:
          repo: dockerregistry.ollioddi.dk/ollioddi/linefever
          registry: dockerregistry.ollioddi.dk
          tags:
              - latest
              - ${DRONE_SEMVER_SHORT}
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
    - name: publish_release
      image: plugins/github-release
      settings:
          api_key:
              from_secret: github_api
trigger:
    ref:
        - refs/tags/*
---
kind: pipeline
type: docker
name: Build beta
steps:
    - name: test
      image: node
      commands:
          - npm install
          - npx prisma generate
          - npm test
    - name: docker_build
      image: plugins/docker
      settings:
          repo: dockerregistry.ollioddi.dk/ollioddi/linefever-beta
          registry: dockerregistry.ollioddi.dk
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
trigger:
    branch:
        - develop
